using System;
using System.Collections.Generic;
using UnityEngine;

public class RankingSystem : MonoBehaviour
{
    public static RankingSystem Instance;

    [SerializeField] private TimeSystem timeSystem;
    [SerializeField] private long minQualifyingScore = 100;
    [SerializeField] private float revenueDivisor = 100f;

    // 정렬된(내림차순) 더미 점수 100개. 비어있으면 Awake에서 자동 채움.
    [SerializeField] private List<long> dummyTop100 = new();

    [Header("자동 생성 설정 (dummyTop100 비어있을 때)")]
    [SerializeField] private bool autoGenerateDummies = true;
    [SerializeField] private long autoDummyTopScore = 50000;   // 1등 점수
    [SerializeField] private long autoDummyBottomScore = 100;  // 100등 점수
    [Tooltip("0=선형, 1=지수 (상위가 훨씬 가파름)")]
    [Range(0f, 1f)]
    [SerializeField] private float autoDummyExpCurve = 0.5f;

    public struct YearResult
    {
        public long Score;
        public bool Qualified;
        public int Rank;        // 1~101 (101 = 더미 전부보다 낮음). Qualified가 false면 0.
        public long Revenue;
        public long Reputation;
    }

    public event Action<YearResult> OnYearRanked;
    public YearResult LastResult { get; private set; }

    private void Awake()
    {
        if (Instance != null && Instance != this) { Destroy(gameObject); return; }
        Instance = this;

        if (autoGenerateDummies && (dummyTop100 == null || dummyTop100.Count == 0))
            GenerateDummyTop100();
    }

    // 더미 100개 자동 생성 (내림차순 정렬됨)
    [ContextMenu("Generate Dummy Top 100")]
    public void GenerateDummyTop100()
    {
        dummyTop100 = new List<long>(100);
        long range = autoDummyTopScore - autoDummyBottomScore;
        for (int i = 0; i < 100; i++)
        {
            float t = i / 99f; // 0(1등) ~ 1(100등)
            // 선형(t)과 지수(t^2) 사이 보간
            float curved = Mathf.Lerp(t, t * t, autoDummyExpCurve);
            long score = autoDummyTopScore - (long)(range * curved);
            dummyTop100.Add(score);
        }
        Debug.Log($"[RankingSystem] dummyTop100 자동 생성: 1등={dummyTop100[0]}, 50등={dummyTop100[49]}, 100등={dummyTop100[99]}");
    }

    private void Start()
    {
        timeSystem.OnYearEnded += HandleYearEnded;
    }

    private void OnDestroy()
    {
        if (timeSystem != null) timeSystem.OnYearEnded -= HandleYearEnded;
    }

    private void HandleYearEnded()
    {
        long revenue = SalesTracker.Instance.AnnualRevenue;
        long reputation = ReputationSystem.Instance.AnnualReputation;
        long score = (long)(revenue / revenueDivisor) + reputation;

        var result = new YearResult
        {
            Score = score,
            Revenue = revenue,
            Reputation = reputation,
            Qualified = score >= minQualifyingScore,
            Rank = 0,
        };

        if (result.Qualified)
            result.Rank = ComputeRank(score);

        LastResult = result;
        OnYearRanked?.Invoke(result);

        SalesTracker.Instance.ResetAnnual();
        ReputationSystem.Instance.ResetAnnual();
    }

    private int ComputeRank(long score)
    {
        for (int i = 0; i < dummyTop100.Count; i++)
            if (score >= dummyTop100[i]) return i + 1;
        return dummyTop100.Count + 1;
    }
}
