using System;
using System.Collections.Generic;
using UnityEngine;

public class RankingSystem : MonoBehaviour
{
    public static RankingSystem Instance;

    [SerializeField] private TimeSystem timeSystem;
    [SerializeField] private long minQualifyingScore = 100;
    [SerializeField] private float revenueDivisor = 100f;

    // 정렬된(내림차순) 더미 점수 100개. 비어있으면 Awake에서 자동 채움.
    [SerializeField] private List<long> dummyTop100 = new();

    [Header("자동 생성 설정 (dummyTop100 비어있을 때)")]
    [SerializeField] private bool autoGenerateDummies = true;
    [SerializeField] private long autoDummyTopScore = 50000;   // 1등 점수
    [SerializeField] private long autoDummyBottomScore = 100;  // 100등 점수
    [Tooltip("0=선형, 1=지수 (상위가 훨씬 가파름)")]
    [Range(0f, 1f)]
    [SerializeField] private float autoDummyExpCurve = 0.5f;

    public struct YearResult
    {
        public long Score;
        public bool Qualified;
        public int Rank;        // 1~101 (101 = 더미 전부보다 낮음). Qualified가 false면 0.
        public long Revenue;
        public long Reputation;
    }

    public event Action<YearResult> OnYearRanked;
    public YearResult LastResult { get; private set; }

    private void Awake()
    {
        if (Instance != null && Instance != this) { Destroy(gameObject); return; }
        Instance = this;

        if (autoGenerateDummies && (dummyTop100 == null || dummyTop100.Count == 0))
            GenerateDummyTop100();
    }

    // 더미 100개 자동 생성 (내림차순 정렬됨)
    [ContextMenu("Generate Dummy Top 100")]
    public void GenerateDummyTop100()
    {
        dummyTop100 = new List<long>(100);
        long range = autoDummyTopScore - autoDummyBottomScore;
        for (int i = 0; i < 100; i++)
        {
            float t = i / 99f; // 0(1등) ~ 1(100등)
            // 선형(t)과 지수(t^2) 사이 보간
            float curved = Mathf.Lerp(t, t * t, autoDummyExpCurve);
            long score = autoDummyTopScore - (long)(range * curved);
            dummyTop100.Add(score);
        }
    }

    private void Start()
    {
        timeSystem.OnYearEnded += HandleYearEnded;
    }

    private void OnDestroy()
    {
        if (timeSystem != null) timeSystem.OnYearEnded -= HandleYearEnded;
    }

    private void HandleYearEnded()
    {
        long revenue = SalesTracker.Instance.AnnualRevenue;
        long reputation = ReputationSystem.Instance.AnnualReputation;
        long score = (long)(revenue / revenueDivisor) + reputation;

        var result = new YearResult
        {
            Score = score,
            Revenue = revenue,
            Reputation = reputation,
            Qualified = score >= minQualifyingScore,
            Rank = 0,
        };

        if (result.Qualified)
            result.Rank = ComputeRank(score);

        LastResult = result;
        OnYearRanked?.Invoke(result);

        SalesTracker.Instance.ResetAnnual();
        ReputationSystem.Instance.ResetAnnual();
    }

    private int ComputeRank(long score)
    {
        for (int i = 0; i < dummyTop100.Count; i++)
            if (score >= dummyTop100[i]) return i + 1;
        return dummyTop100.Count + 1;
    }

    // ─── Save / Load ───
    // 직전 연말 정산 결과(LastResult)만 저장. dummyTop100은 SO처럼 고정 데이터라 미저장.
    public RankingData ToData()
    {
        // 정산 한 번도 안 했으면 default 구조체 — Score/Revenue/Reputation 모두 0
        if (LastResult.Score == 0 && LastResult.Revenue == 0 && LastResult.Reputation == 0 && LastResult.Rank == 0)
            return new RankingData { hasLastResult = false };

        return new RankingData
        {
            hasLastResult = true,
            score         = LastResult.Score,
            qualified     = LastResult.Qualified,
            rank          = LastResult.Rank,
            revenue       = LastResult.Revenue,
            reputation    = LastResult.Reputation,
        };
    }

    public void FromData(RankingData data)
    {
        if (data == null || !data.hasLastResult)
        {
            LastResult = default;
            return;
        }

        LastResult = new YearResult
        {
            Score      = data.score,
            Qualified  = data.qualified,
            Rank       = data.rank,
            Revenue    = data.revenue,
            Reputation = data.reputation,
        };
        // 이벤트 발화 X — UI는 패널 열 때 LastResult 조회로 재구성하면 됨
    }
}
